### ISSUE TITLE
The mongo docker inside the tutorials requires 3379MB of free disk space

### ISSUE THREAD

**Issue by perellonieto** [IRC-SPHERE/Hyperstream-Dockerfiles#11]
This can be an issue only on my machine as I need to increase my disk space. However, for the purpose of running the tutorial, I do not find necessary to require this minimum of free disk space. For the moment, the tutorial should not require more than some MB of free space. Only enough to run the docker containers but not much for the MongoDB.

I have been able to solve this problem in the main Dockerfile with the commit edcf177ded5f53abfbd91b9498196de660ff2394. However, it seems that this solution does not affect the tutorial composition.

Does somebody have an idea about how to incorporate the change that I did in tutorial composition?

**Comment by So-Cool** [comment]
It does not affect the tutorial composition because it ha snot been pushed to the docker hub. I'm setting it up right now.
