### ISSUE TITLE
HyperStreamViewer does not produce a functional website

### ISSUE THREAD

**Issue by So-Cool** [IRC-SPHERE/Hyperstream-Dockerfiles#2]
Once the [IRC-SPHERE/HyperStream PR5](https://github.com/IRC-SPHERE/HyperStream/pull/5) is merged this will build just fine with:
```
docker-compose build
```

When you run it with:
```
docker-compose up
```
and point your browser to [`http://127.0.0.1:5000/`](http://127.0.0.1:5000/) you get the following error:
```
werkzeug.routing.BuildError
BuildError: Could not build url for endpoint 'bower.static' with values ['filename']. Did you mean 'static' instead?
```

Any hints @tdiethe?  
Maybe it's because I have removed these lines form the `hyperstream_config.json`'s plugins section:
```
        {
            "channel_id_prefix": "sphere",
            "path": "plugins/sphere",
            "channel_names": ["sphere_channel", "summary_channel"],
            "has_tools": true,
            "has_assets": true
        }
```

**Comment by tdiethe** [comment]
Has bower update been run?
