### ISSUE TITLE
Jupyter notebook 4.3.0 requires authentication

### ISSUE THREAD

**Issue by perellonieto** [IRC-SPHERE/Hyperstream-Dockerfiles#7]
From Jupyter notebook 4.3.0 it is required a token or a password to access the web-page.

The token is generated randomly by Jupyter and the URL with the token is presented in the terminal running the notebook. E.g.
```bash
hyperstream_1         |     Copy/paste this URL into your browser when you connect for the first time,
hyperstream_1         |     to login with a token:
hyperstream_1         |         http://0.0.0.0:8888/?token=4b45b0b80b27c9470db711ee967c61620872350a5deceb02
```
This is to increase the security of Jupyter notebook. But makes more difficult to access to the tutorial as the token is randomized. There is the possibility of disabling the password and token by adding this two lines into the configuration file jupyter_notebook_config.json

```
c.NotebookApp.token = ''
c.NotebookApp.password = ''
```
As the notebook is running in a Docker, I don't think this could bring the user to be exposed to any system vulnerability. However, I think the token could be used as a safety measure, to be sure that the user following the tutorial is connecting to our Docker instance, and not to any other page (what I think would be unlikely).

More info about the problem see [this discussion][1]. Or the documentation explaining the [security in the Jupyter notebook server][2].

[1]: https://github.com/jupyter/notebook/issues/1979
[2]: http://jupyter-notebook.readthedocs.io/en/latest/security.html

**Comment by tdiethe** [comment]
Good catch. I think it's fine to disable the token in this setting.

**Comment by perellonieto** [comment]
I close this as the new method to open the tutorials is explained in the Readme file.
It would be nice to consider the option of removing the password but this may require further discussions about security issues.

**Comment by So-Cool** [comment]
I think that with the newest jupyter version it's almost impossible to disable the token, but it is possible to replace it with login/password. Therefore, it might be worth changing the token into login:hypersteram, password:hyperstrem.
