### ISSUE TITLE
HyperStream-tutorials loads an old version of HyperStream

### ISSUE THREAD

**Issue by perellonieto** [IRC-SPHERE/Hyperstream-Dockerfiles#8]
When you start the docker for HyperStream, this downloads the last version 0.3.6 and runs the test. However, when you start the tutorial with
```
docker-compose -f docker-compose-tutorials.yml -p hyperstream-tutorials up
```
When running the tutorials the HyperStream version is 0.3.0

I think the reason that the _HyperStream/Dockerfile_ starts `FROM ubuntu:16.04` and then downloads the master branch of HyperStream from GitHub.
However, the _HyperStream-tutorials/Dockerfile_ starts `FROM ircsphere/hyperstream` and does not download the last version of HyperStream from GitHub. I assume that in this case it loads the Docker version from [hub.docker][1] which has a tag _latest_ from a month ago.

Should we keep the docker version in [hub.docker updated][2]? Or should we follow the same approach than the HyperStream one by downloading all the dependencies from GitHub?

[1]: https://hub.docker.com/r/ircsphere/hyperstream/
[2]: https://docs.docker.com/docker-hub/builds/

**Comment by So-Cool** [comment]
We should definitely update the dockerhub container to have the latest version of hyperstream.

I personally don't have access to the sphere dockerhub account so I cannot do anything about it. @perellonieto do you know who might have access to it?

**Comment by perellonieto** [comment]
It is possible to update the dockerhub, and we should do that. However, I see that the dockerhub intention is to keep stable versions and not a branch that is constantly changing (as it creates an image and stores it already precompiled in the cloud).
There is a way to keep the dockerhub version up to date with every commit, but in that case, I think we should keep a branch with the stable versions or develop always in other branches and keep the master clean only with stable versions.

**Comment by tdiethe** [comment]
I did try to set up dockerhub to have automated builds before I left, but I just checked the logs and it's failing (obviously in hindsight) because it expects the docker config to be in the main repository:

```
Logs
Building in Docker Cloud's infrastructure...
Cloning into '.'...

Dockerfile not found at ./Dockerfile
```

This is all administered under the `ircsphere` organisation on docker hub - if you guys create accounts on there I can add you as owners of that organisation.

**Comment by So-Cool** [comment]
@tdiethe My docker hub user id is so8cool

**Comment by tdiethe** [comment]
@So-Cool done

**Comment by perellonieto** [comment]
I partially solved this problem by adding the Dockerfile used in this repo IRC-SPHERE/HyperStream-Dockerfiles/blob/master/HyperStream/Dockerfile to IRC-SPHERE/HyperStream/blob/master/Dockerfile

Now https://hub.docker.com/r/ircsphere/hyperstream/builds/ shows the master branch with the latest version as a success.

However, I assume that there is some reason not to follow this approach as Kacper was using this other GitHub repo to store the Dockerfile.

@So-Cool Could you tell me if what I did is good enough or if we should follow some other approach?

**Comment by perellonieto** [comment]
I tried the tutorial now that  hub.docker has the last version of HyperStream but when I run the Jupyter notebook the watermark still shows the Hyperstream with version 0.3.0-beta.

**Comment by perellonieto** [comment]
I tried again after cleaning the docker images in my machine and it is working with the last version.

**Comment by So-Cool** [comment]
@perellonieto I don't think that we should duplicate the `Dockerfile` in the HyperStream repo. You can actually make an automatic build from an external repository. To that end, I'll have to delete and recreate the HyperStream repo on the Docker Hub.

I'll also remove the `Dockerfile` from the IRC-SPHERE/hyperstream repo.

I hope that it's OK; if not feel free to reopen this issue and we can discuss the issue further.
